In [1]:
import pandas as pd
r=pd.read_csv('/content/train.csv')
print(r)
x=r['price_range']
print(x)
y=r.drop('price_range',axis=1)
print(y)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       

In [10]:
minimum=np.min(x)
maximum=np.max(x)
print(minimum)
print(maximum)
list_y=[]
for i in x:
  y_value=((i-minimum)/maximum-minimum)
  y_value=y_value*(1-0)
  list_y.append(y_value)
print(list_y)

0
3
[0.3333333333333333, 0.6666666666666666, 0.6666666666666666, 0.6666666666666666, 0.3333333333333333, 0.3333333333333333, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.3333333333333333, 0.6666666666666666, 0.0, 0.0, 1.0, 1.0, 0.3333333333333333, 0.3333333333333333, 1.0, 1.0, 0.3333333333333333, 0.0, 0.3333333333333333, 0.6666666666666666, 1.0, 1.0, 0.6666666666666666, 0.0, 1.0, 0.0, 0.3333333333333333, 1.0, 0.0, 0.3333333333333333, 0.3333333333333333, 1.0, 0.6666666666666666, 0.6666666666666666, 0.6666666666666666, 1.0, 0.3333333333333333, 0.3333333333333333, 0.0, 0.3333333333333333, 1.0, 0.3333333333333333, 0.0, 1.0, 0.6666666666666666, 0.6666666666666666, 1.0, 0.3333333333333333, 0.6666666666666666, 0.6666666666666666, 0.0, 1.0, 0.3333333333333333, 0.6666666666666666, 0.3333333333333333, 0.0, 0.0, 0.6666666666666666, 0.6666666666666666, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.6666666666666666, 0.0, 1.0, 0.0, 0.3333333333333333, 0.0, 0.0, 1.0, 0.3333333333333333, 1.0, 0.6666666666666666, 1.0, 0.33333333

In [2]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))
c=scaler.fit_transform(y)
print(c)
print(c.shape)

[[0.22778891 0.         0.68       ... 0.         0.         1.        ]
 [0.34736139 1.         0.         ... 1.         1.         0.        ]
 [0.04141617 1.         0.         ... 1.         1.         0.        ]
 ...
 [0.94188377 0.         0.16       ... 1.         1.         0.        ]
 [0.6753507  0.         0.16       ... 1.         1.         1.        ]
 [0.00601202 1.         0.6        ... 1.         1.         1.        ]]
(2000, 20)


In [3]:
import pandas as pd
a=pd.read_csv('/content/test.csv')
print(a)

       id  battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0       1           1043     1          1.8         1  14       0           5   
1       2            841     1          0.5         1   4       1          61   
2       3           1807     1          2.8         0   1       0          27   
3       4           1546     0          0.5         1  18       1          25   
4       5           1434     0          1.4         0  11       1          49   
..    ...            ...   ...          ...       ...  ..     ...         ...   
995   996           1700     1          1.9         0   0       1          54   
996   997            609     0          1.8         1   0       0          13   
997   998           1185     0          1.4         0   1       1           8   
998   999           1533     1          0.5         1   0       0          50   
999  1000           1270     1          0.5         0   4       1          35   

     m_dep  mobile_wt  ... 

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(c,x,test_size=0.21)
print(x_train)

print(x_test)

print(y_train)

print(y_test)
print(x_train.shape)
print(y_test.shape)
print(y_train.shape)
print(x_test.shape)

[[0.71342685 1.         0.44       ... 1.         0.         0.        ]
 [0.48964596 0.         0.48       ... 0.         0.         1.        ]
 [0.73947896 0.         0.52       ... 0.         0.         1.        ]
 ...
 [0.60387442 0.         0.48       ... 0.         1.         0.        ]
 [0.88777555 1.         0.2        ... 1.         0.         0.        ]
 [0.21509686 1.         0.         ... 0.         0.         1.        ]]
[[0.57247829 1.         0.         ... 1.         1.         0.        ]
 [0.30460922 1.         0.8        ... 1.         0.         1.        ]
 [0.24248497 1.         1.         ... 1.         1.         1.        ]
 ...
 [0.55711423 1.         1.         ... 1.         0.         0.        ]
 [0.95190381 1.         0.48       ... 1.         0.         0.        ]
 [0.9492318  0.         0.         ... 1.         0.         0.        ]]
1670    3
1870    2
445     0
593     3
1510    1
       ..
912     2
1010    2
1934    2
1787    3
279     0
Na

In [5]:
import pandas as pd
q=pd.read_csv('/content/heart.csv')
print(q)
w=q['target']
print(w)
e=q.drop('target',axis=1)
print(e)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2     

In [6]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))
xtrain_norm=scaler.fit_transform(e)
print(xtrain_norm)
print(xtrain_norm.shape)

[[0.70833333 1.         1.         ... 0.         0.         0.33333333]
 [0.16666667 1.         0.66666667 ... 0.         0.         0.66666667]
 [0.25       0.         0.33333333 ... 1.         0.         0.66666667]
 ...
 [0.8125     1.         0.         ... 0.5        0.5        1.        ]
 [0.58333333 1.         0.         ... 0.5        0.25       1.        ]
 [0.58333333 0.         0.33333333 ... 0.5        0.25       0.66666667]]
(303, 13)


In [7]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(xtrain_norm,w,test_size=0.2,random_state=42)
print(xtrain)
print(xtest)
print(ytrain)
print(ytest)
print(xtrain.shape)
print(xtest.shape)
print(ytrain.shape)
print(ytest.shape)

[[0.27083333 1.         0.33333333 ... 1.         0.         0.66666667]
 [0.60416667 1.         0.         ... 1.         0.         1.        ]
 [0.35416667 1.         0.66666667 ... 0.5        0.         0.66666667]
 ...
 [0.83333333 1.         1.         ... 0.5        0.25       0.66666667]
 [0.35416667 1.         0.         ... 1.         0.         1.        ]
 [0.70833333 0.         0.33333333 ... 1.         0.5        0.66666667]]
[[0.58333333 1.         0.         0.52830189 0.34246575 0.
  0.         0.3129771  1.         0.09677419 0.5        0.25
  0.33333333]
 [0.625      1.         1.         0.71698113 0.36986301 0.
  0.         0.67175573 0.         0.03225806 0.5        0.
  1.        ]
 [0.58333333 1.         0.66666667 0.52830189 0.         1.
  0.5        0.77862595 0.         0.03225806 1.         0.25
  1.        ]
 [0.5625     0.         0.         0.37735849 0.64611872 0.
  0.         0.60305344 1.         0.30645161 0.5        0.5
  1.        ]
 [0.875      0.

In [8]:
x01=xtrain[12]
print(x01)
x02=xtrain[12]
print(x02)

[0.39583333 1.         0.         0.26415094 0.21917808 0.
 0.         0.8778626  0.         0.         1.         0.
 0.66666667]
[0.39583333 1.         0.         0.26415094 0.21917808 0.
 0.         0.8778626  0.         0.         1.         0.
 0.66666667]


In [12]:
x01=x_train[0]
x02=x_train[1]
x03=x_train[2]
x04=x_train[3]
x05=x_train[4]
x06=x_train[5]
x07=x_train[6]
x08=x_train[7]
x09=x_train[8]
x10=x_train[9]
x11=x_train[10]
x12=x_train[11]
x13=x_train[12]
y_p=[]
def perceptron(w1,w2,w3,w4,w5,w6,w7,w8,w9,w10,w11,w12,w13,b):
  for i in range(len(x01)):
    z=x01[i]*w1+x02[i]*w2+x03[i]*w3+x04[i]*w4+x05[i]*w5+x06[i]*w6+x07[i]*w7+x08[i]*w8+x09[i]*w9+x10[i]*w10+x11[i]*w11+x12[i]*w12+x13[i]*w13+b
    s=1/1+np.exp(-z)
    if (s>=0.5):
      y_p.append(1)
    else:
      y_p.append(0)
  return y_p

print(perceptron(1,2,3,1,2,3,1,2,3,1,2,3,1,10))

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
